version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7-node-browsers
        environment:
          RUBYOPT: "-W:no-deprecated -W:no-experimental"
    steps:
      - checkout

      - run: echo 127.0.0.1 blog.localhost | sudo tee -a /etc/hosts

      # One of the apps needs hugo
      - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends hugo

      # Make sure we use the right Bundler
      - run: gem install bundler --version `tail -1 Gemfile.lock`

      # Bundle install dependencies
      - type: cache-restore
        key: v1-main-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies for example app
      - type: cache-restore
        key: v1-example-{{ checksum "example/Gemfile.lock" }}

      # Yarn dependencies
      - restore_cache:
          keys:
            - v2-yarn-{{ checksum "example/yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-yarn-

      # Bundle install dependencies for jekyll app
      - type: cache-restore
        key: v1-jekyll-{{ checksum "example/static/docs/Gemfile.lock" }}

      # Npm install for Eleventy app
      - restore_cache:
          keys:
            - v1-eleventy-{{ checksum "example/static/blog-docs/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-eleventy-

      - run: ./script/setup

      - type: cache-save
        key: v1-main-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: cache-save
        key: v1-example-{{ checksum "example/Gemfile.lock" }}
        paths:
          - example/vendor/bundle

      - save_cache:
          paths:
            - example/node_modules
            - ~/.cache
          key: v2-yarn-{{ checksum "example/yarn.lock" }}

      - type: cache-save
        key: v1-jekyll-{{ checksum "example/static/docs/Gemfile.lock" }}
        paths:
          - example/static/docs/vendor/bundle

      - save_cache:
          paths:
            - example/static/blog-docs/node_modules
          key: v1-eleventy-{{ checksum "example/static/blog-docs/package-lock.json" }}

      - run: ./script/test
